name-template: 'Production Release — $DATE'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: "### What's New"
    labels:
      - 'feature'
    # For features, we show the Title and the full Description
    change-template: |
      * **$TITLE**
        $BODY
  - title: '#### $VALUE' 
    labels:
      - 'improvement/*'
    # For bugs/others, we just show the Title
    change-template: '* $TITLE'

# Remove the (@$AUTHOR) if it exists globally
change-template: '* $TITLE'

template: |
  # Production Release — $DATE

  $CHANGES
