name-template: 'Production Release — $DATE'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: "### What's New"
    labels:
      - 'feature'
    change-template: |
      * **$TITLE**
        $BODY
  - title: '### $VALUE' # This ensures the label name becomes a ### heading
    labels:
      - 'improvement/*'
    change-template: |
      * **$TITLE**
        $BODY

# Remove the (@$AUTHOR) if it exists globally
change-template: '* $TITLE'

template: |
  # Production Release — $DATE

  $CHANGES
